-- ============================================================
-- PortFlux �봽濡쒖젥�듃 �뜲�씠�꽣踰좎씠�뒪 �뒪�겕由쏀듃 (�닔�젙蹂�)
-- �옉�꽦�씪: 2025-12-30
-- �꽕紐�: �쟾泥� �뀒�씠釉� �깮�꽦 諛� �깦�뵆 �뜲�씠�꽣 �궫�엯
-- ============================================================

-- �븞�쟾�븳 �뀒�씠釉� �궘�젣 (議댁옱�븯�뒗 寃쎌슦留�)
BEGIN
    FOR t IN (SELECT table_name FROM user_tables 
              WHERE table_name IN ('PAYMENTS', 'PAY', 'ORDER_ITEMS', 'ORDERS', 
                                   'COMMENT_LIKE', 'POST_LIKE', 'CART', 
                                   'CHAT_MESSAGE_FILES', 'CHAT_MESSAGES', 
                                   'DIRECT_CHAT_ROOMS', 'FOLLOWS', 'POST_SAVE', 
                                   'POST_COMMENT', 'POST', 'ADMIN_ACCOUNT', 
                                   'COMPANY', 'USERS'))
    LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

------------------------------------------------------------
-- 1) USERS �뀒�씠釉�
------------------------------------------------------------
CREATE TABLE USERS (
    user_num NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR2(50) NOT NULL UNIQUE,
    user_password VARCHAR2(100) NOT NULL,
    user_name VARCHAR2(100) NOT NULL,
    user_phone VARCHAR2(20),
    user_email VARCHAR2(255) NOT NULL,
    user_nickname VARCHAR2(100) NOT NULL,
    drawn_user CHAR(1) DEFAULT 'N',
    user_create_at DATE DEFAULT SYSDATE NOT NULL,
    user_level NUMBER(2),
    user_image BLOB,
    user_banner BLOB
);

------------------------------------------------------------
-- 2) COMPANY �뀒�씠釉�
------------------------------------------------------------
CREATE TABLE COMPANY (
    company_num NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id VARCHAR2(50) NOT NULL UNIQUE,
    company_password VARCHAR2(100) NOT NULL,
    company_name VARCHAR2(100) NOT NULL,
    company_phone VARCHAR2(20) NOT NULL,
    company_email VARCHAR2(255) NOT NULL,
    drawn_company CHAR(1) DEFAULT 'N',
    company_create_at DATE DEFAULT SYSDATE,
    company_image BLOB,
    company_banner BLOB,
    business_number VARCHAR2(20) NOT NULL UNIQUE
);

------------------------------------------------------------
-- 3) ADMIN_ACCOUNT �뀒�씠釉�
------------------------------------------------------------
CREATE TABLE ADMIN_ACCOUNT (
    admin_num NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_num NUMBER(20) NOT NULL,
    admin_id VARCHAR2(50) NOT NULL UNIQUE,
    admin_password VARCHAR2(100) NOT NULL,
    admin_name VARCHAR2(100),
    assigned_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_admin_user FOREIGN KEY (user_num) REFERENCES USERS(user_num) ON DELETE CASCADE
);

COMMENT ON TABLE ADMIN_ACCOUNT IS '愿�由ъ옄 怨꾩젙 �젙蹂�';
COMMENT ON COLUMN ADMIN_ACCOUNT.user_num IS 'USERS �뀒�씠釉붿쓽 �쉶�썝 踰덊샇';

------------------------------------------------------------
-- 4) POST �뀒�씠釉�
------------------------------------------------------------
CREATE TABLE POST (
    post_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_type VARCHAR2(10) NOT NULL,
    user_num NUMBER(20),
    company_num NUMBER(20),
    title VARCHAR2(255) NOT NULL,
    content VARCHAR2(4000) NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE DEFAULT SYSDATE NOT NULL,
    view_cnt NUMBER DEFAULT 0,
    price NUMBER(10),
    ai_summary VARCHAR2(500),
    download_cnt NUMBER DEFAULT 0,
    post_file VARCHAR2(255),
    like_cnt NUMBER DEFAULT 0,
    image VARCHAR2(255),
    tags VARCHAR2(2000),
    -- 梨꾩슜怨듦퀬 愿��젴 而щ읆
    job_region VARCHAR2(100),
    job_career_type VARCHAR2(500),
    job_career_years VARCHAR2(500),
    job_education VARCHAR2(50),
    job_education_exclude CHAR(1) DEFAULT 'N',
    job_salary_min NUMBER(10),
    job_salary_max NUMBER(10),
    job_deadline DATE,
    job_status VARCHAR2(20) DEFAULT 'ACTIVE',
    job_industries VARCHAR2(500),
    job_company_types VARCHAR2(500),
    job_work_types VARCHAR2(500),
    job_work_days VARCHAR2(500),
    company_logo CLOB, -- 梨꾩슜怨듦퀬 �쟾�슜 湲곗뾽 濡쒓퀬 (Base64)
    company_phone VARCHAR2(20), -- 梨꾩슜怨듦퀬 臾몄쓽 �쟾�솕踰덊샇
    -- �젣�빟議곌굔
    CONSTRAINT ck_post_board_type CHECK (board_type IN ('lookup', 'job', 'free', 'notice')),
    CONSTRAINT ck_post_author_unified CHECK (
        ((board_type IN ('free', 'lookup', 'notice')) AND (user_num IS NOT NULL OR company_num IS NOT NULL))
        OR (board_type = 'job' AND company_num IS NOT NULL)
    ),
    CONSTRAINT ck_job_required_fields CHECK (
        (board_type = 'job' AND job_region IS NOT NULL AND job_deadline IS NOT NULL AND job_status IS NOT NULL)
        OR board_type IN ('lookup', 'free', 'notice')
    ),
    CONSTRAINT ck_job_status CHECK (
        job_status IN ('ACTIVE', 'EXPIRED', 'CLOSED') OR job_status IS NULL
    ),
    CONSTRAINT fk_post_user FOREIGN KEY (user_num) REFERENCES USERS(user_num) ON DELETE SET NULL,
    CONSTRAINT fk_post_company FOREIGN KEY (company_num) REFERENCES COMPANY(company_num) ON DELETE SET NULL
);

-- POST �씤�뜳�뒪
CREATE INDEX idx_post_tags ON POST(tags);
CREATE INDEX idx_post_job_deadline ON POST(job_deadline);
CREATE INDEX idx_post_job_region ON POST(job_region);
CREATE INDEX idx_post_job_status ON POST(job_status);
CREATE INDEX idx_post_job_search ON POST(board_type, job_status, job_deadline);

-- POST �듃由ш굅
CREATE OR REPLACE TRIGGER trg_post_update
BEFORE UPDATE ON POST
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;
/

------------------------------------------------------------
-- 5) POST_COMMENT �뀒�씠釉�
------------------------------------------------------------
CREATE TABLE POST_COMMENT (
    comment_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id NUMBER(20) NOT NULL,
    user_num NUMBER(20),
    company_num NUMBER(20),
    comment_content VARCHAR2(1000),
    comment_created_at DATE DEFAULT SYSDATE,
    comment_modify_at DATE,
    parent_id NUMBER(20),
    CONSTRAINT ck_comment_author CHECK (user_num IS NOT NULL OR company_num IS NOT NULL),
    CONSTRAINT fk_comment_user FOREIGN KEY (user_num) REFERENCES USERS(user_num) ON DELETE SET NULL,
    CONSTRAINT fk_comment_post FOREIGN KEY (post_id) REFERENCES POST(post_id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_company FOREIGN KEY (company_num) REFERENCES COMPANY(company_num) ON DELETE SET NULL
);

------------------------------------------------------------
-- 6) POST_SAVE �뀒�씠釉� (�씪諛� �궗�슜�옄 + 湲곗뾽 �쉶�썝 遺곷쭏�겕 吏��썝)
------------------------------------------------------------
CREATE TABLE POST_SAVE (
    board_save_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_save_time DATE DEFAULT SYSDATE NOT NULL,
    user_num NUMBER(20),
    company_num NUMBER(20),
    post_id NUMBER(20) NOT NULL,
    CONSTRAINT ck_save_author CHECK (user_num IS NOT NULL OR company_num IS NOT NULL),
    CONSTRAINT fk_save_user FOREIGN KEY (user_num) REFERENCES USERS(user_num) ON DELETE CASCADE,
    CONSTRAINT fk_save_company FOREIGN KEY (company_num) REFERENCES COMPANY(company_num) ON DELETE CASCADE,
    CONSTRAINT fk_save_post FOREIGN KEY (post_id) REFERENCES POST(post_id) ON DELETE CASCADE
);

-- POST_SAVE 以묐났 諛⑹� �쑀�땲�겕 �씤�뜳�뒪 (�븿�닔 湲곕컲)
-- user_num�씠 �엳�뒗 寃쎌슦�쓽 �쑀�땲�겕 �젣�빟
CREATE UNIQUE INDEX idx_post_save_user_unique
    ON POST_SAVE(
        CASE WHEN user_num IS NOT NULL THEN user_num END,
        CASE WHEN user_num IS NOT NULL THEN post_id END
    );

-- company_num�씠 �엳�뒗 寃쎌슦�쓽 �쑀�땲�겕 �젣�빟
CREATE UNIQUE INDEX idx_post_save_company_unique
    ON POST_SAVE(
        CASE WHEN company_num IS NOT NULL THEN company_num END,
        CASE WHEN company_num IS NOT NULL THEN post_id END
    );

------------------------------------------------------------
-- 7) FOLLOWS �뀒�씠釉�
------------------------------------------------------------
CREATE TABLE FOLLOWS (
    follow_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id NUMBER(20) NOT NULL,
    following_id NUMBER(20) NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_follows_follower FOREIGN KEY (follower_id) REFERENCES USERS(user_num) ON DELETE CASCADE,
    CONSTRAINT fk_follows_following FOREIGN KEY (following_id) REFERENCES USERS(user_num) ON DELETE CASCADE
);

------------------------------------------------------------
-- 8) DIRECT_CHAT_ROOMS �뀒�씠釉�
------------------------------------------------------------
CREATE TABLE DIRECT_CHAT_ROOMS (
    room_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user1_num NUMBER(20) NOT NULL,
    user2_num NUMBER(20) NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    last_message_at DATE,
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT fk_chatroom_user1 FOREIGN KEY (user1_num) REFERENCES USERS(user_num),
    CONSTRAINT fk_chatroom_user2 FOREIGN KEY (user2_num) REFERENCES USERS(user_num)
);

------------------------------------------------------------
-- 9) CHAT_MESSAGES �뀒�씠釉�
------------------------------------------------------------
CREATE TABLE CHAT_MESSAGES (
    message_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id NUMBER(20) NOT NULL,
    user_num NUMBER(20) NOT NULL,
    sender_num NUMBER(20) NOT NULL,
    content VARCHAR2(2000),
    has_file CHAR(1) DEFAULT 'N' NOT NULL,
    sent_at DATE DEFAULT SYSDATE NOT NULL,
    read_yn CHAR(1) DEFAULT 'N' NOT NULL,
    deleted_yn CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT fk_message_room FOREIGN KEY (room_id) REFERENCES DIRECT_CHAT_ROOMS(room_id) ON DELETE CASCADE,
    CONSTRAINT fk_message_user FOREIGN KEY (user_num) REFERENCES USERS(user_num),
    CONSTRAINT fk_message_sender FOREIGN KEY (sender_num) REFERENCES USERS(user_num)
);

------------------------------------------------------------
-- 10) CHAT_MESSAGE_FILES �뀒�씠釉�
------------------------------------------------------------
CREATE TABLE CHAT_MESSAGE_FILES (
    file_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id NUMBER(20) NOT NULL,
    file_name VARCHAR2(255) NOT NULL,
    mime_type VARCHAR2(100),
    file_size NUMBER(20),
    file_path VARCHAR2(1000),
    file_data BLOB,
    uploaded_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_file_message FOREIGN KEY (message_id) REFERENCES CHAT_MESSAGES(message_id) ON DELETE CASCADE
);

------------------------------------------------------------
-- 11) CART �뀒�씠釉�
------------------------------------------------------------
CREATE TABLE CART (
    cart_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_num NUMBER(20) NOT NULL,
    post_id NUMBER(20) NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_cart_user FOREIGN KEY (user_num) REFERENCES USERS(user_num) ON DELETE CASCADE,
    CONSTRAINT fk_cart_post FOREIGN KEY (post_id) REFERENCES POST(post_id) ON DELETE CASCADE
);

------------------------------------------------------------
-- 12) ORDERS �뀒�씠釉� (二쇰Ц �궡�뿭 愿�由�)
------------------------------------------------------------
CREATE TABLE ORDERS (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id NUMBER(20) NOT NULL,
    merchant_uid VARCHAR2(255) NOT NULL,
    total_amount NUMBER(19,2) NOT NULL,
    status VARCHAR2(50) NOT NULL,
    imp_uid VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_orders_merchant_uid UNIQUE (merchant_uid),
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES USERS(user_num)
);

CREATE INDEX idx_orders_merchant_uid ON ORDERS(merchant_uid);
CREATE INDEX idx_orders_user_id ON ORDERS(user_id);
CREATE INDEX idx_orders_created_at ON ORDERS(created_at);

COMMENT ON TABLE ORDERS IS '二쇰Ц �궡�뿭 愿�由� �뀒�씠釉�';
COMMENT ON COLUMN ORDERS.merchant_uid IS '二쇰Ц 怨좎쑀 �떇蹂꾩옄 (UUID 湲곕컲)';
COMMENT ON COLUMN ORDERS.status IS '二쇰Ц �긽�깭 (CREATED, PENDING, PAID, CANCELLED)';

------------------------------------------------------------
-- 13) ORDER_ITEMS �뀒�씠釉� (二쇰Ц �긽�뭹 �긽�꽭)
------------------------------------------------------------
CREATE TABLE ORDER_ITEMS (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    product_id NUMBER(20) NOT NULL,
    product_name VARCHAR2(500) NOT NULL,
    unit_price NUMBER(19,2) NOT NULL,
    qty NUMBER NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES ORDERS(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES POST(post_id)
);

CREATE INDEX idx_order_items_order_id ON ORDER_ITEMS(order_id);
CREATE INDEX idx_order_items_product_id ON ORDER_ITEMS(product_id);

COMMENT ON TABLE ORDER_ITEMS IS '二쇰Ц �긽�뭹 �긽�꽭 �젙蹂�';
COMMENT ON COLUMN ORDER_ITEMS.qty IS '二쇰Ц �닔�웾';

------------------------------------------------------------
-- 14) POST_LIKE �뀒�씠釉� (寃뚯떆湲� 醫뗭븘�슂)
------------------------------------------------------------
CREATE TABLE POST_LIKE (
    like_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    post_id NUMBER(20) NOT NULL,
    user_num NUMBER(20),
    company_num NUMBER(20),
    liked_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uq_post_like_unified UNIQUE (post_id, user_num, company_num),
    CONSTRAINT ck_like_author CHECK (user_num IS NOT NULL OR company_num IS NOT NULL),
    CONSTRAINT fk_postlike_user FOREIGN KEY (user_num) REFERENCES USERS(user_num) ON DELETE SET NULL,
    CONSTRAINT fk_postlike_post FOREIGN KEY (post_id) REFERENCES POST(post_id) ON DELETE CASCADE,
    CONSTRAINT fk_postlike_company FOREIGN KEY (company_num) REFERENCES COMPANY(company_num) ON DELETE SET NULL
);

------------------------------------------------------------
-- 15) COMMENT_LIKE �뀒�씠釉� (�뙎湲� 醫뗭븘�슂)
------------------------------------------------------------
CREATE TABLE COMMENT_LIKE (
    like_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_num NUMBER(20) NOT NULL,
    comment_id NUMBER(20) NOT NULL,
    liked_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uq_comment_like UNIQUE (user_num, comment_id),
    CONSTRAINT fk_commentlike_user FOREIGN KEY (user_num) REFERENCES USERS(user_num) ON DELETE CASCADE,
    CONSTRAINT fk_commentlike_comment FOREIGN KEY (comment_id) REFERENCES POST_COMMENT(comment_id) ON DELETE CASCADE
);

------------------------------------------------------------
-- 16) PAYMENTS �뀒�씠釉� (寃곗젣 湲곕줉 - �븘�엫�룷�듃 �뿰�룞)
------------------------------------------------------------
CREATE TABLE PAYMENTS (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    imp_uid VARCHAR2(255) NOT NULL,
    merchant_uid VARCHAR2(255) NOT NULL,
    amount NUMBER(19,2) NOT NULL,
    status VARCHAR2(50) NOT NULL,
    paid_at TIMESTAMP,
    raw_response CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_payments_imp_uid UNIQUE (imp_uid),
    CONSTRAINT uq_payments_merchant_uid UNIQUE (merchant_uid),
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES ORDERS(id) ON DELETE CASCADE
);

CREATE INDEX idx_payments_order_id ON PAYMENTS(order_id);
CREATE INDEX idx_payments_merchant_uid ON PAYMENTS(merchant_uid);
CREATE INDEX idx_payments_imp_uid ON PAYMENTS(imp_uid);
CREATE INDEX idx_payments_status ON PAYMENTS(status);

COMMENT ON TABLE PAYMENTS IS '寃곗젣 湲곕줉 愿�由� �뀒�씠釉� (�븘�엫�룷�듃 �뿰�룞)';
COMMENT ON COLUMN PAYMENTS.imp_uid IS '�븘�엫�룷�듃 嫄곕옒 怨좎쑀 ID';
COMMENT ON COLUMN PAYMENTS.merchant_uid IS '媛�留뱀젏 二쇰Ц 踰덊샇 (ORDERS.merchant_uid)';
COMMENT ON COLUMN PAYMENTS.status IS '寃곗젣 �긽�깭 (READY, PAID, CANCELLED, REFUNDED)';
COMMENT ON COLUMN PAYMENTS.raw_response IS '�븘�엫�룷�듃 �쓳�떟 �썝蹂� �뜲�씠�꽣 (JSON)';

------------------------------------------------------------
-- 17) PAY �뀒�씠釉� (湲곗〈 寃곗젣 �뀒�씠釉� �쑀吏�)
------------------------------------------------------------
CREATE TABLE PAY (
    order_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_num NUMBER(20) NOT NULL,
    pay_date DATE DEFAULT SYSDATE,
    pay_price NUMBER(20) NOT NULL,
    setle_sttus NUMBER(1) NOT NULL,
    order_name VARCHAR2(200) NOT NULL,
    cart_id NUMBER(20) NOT NULL,
    CONSTRAINT fk_pay_user FOREIGN KEY (user_num) REFERENCES USERS(user_num) ON DELETE CASCADE,
    CONSTRAINT fk_pay_cart FOREIGN KEY (cart_id) REFERENCES CART(cart_id) ON DELETE CASCADE
);

COMMIT;

-- ============================================================
-- �깦�뵆 �뜲�씠�꽣 INSERT
-- ============================================================

-- 1) USERS
INSERT INTO USERS (user_id, user_password, user_name, user_phone, user_email, user_nickname, user_level)
VALUES ('user001', 'password123!', '源�泥좎닔', '010-1234-5678', 'kimcs@email.com', '泥좎닔吏�', 1);

INSERT INTO USERS (user_id, user_password, user_name, user_phone, user_email, user_nickname, user_level)
VALUES ('user002', 'password456!', '�씠�쁺�씗', '010-9876-5432', 'leeyh@email.com', '�쁺�씗�꽕', 2);

-- 1-1) Admin
INSERT INTO USERS (user_id, user_password, user_name, user_phone, user_email, user_nickname)
VALUES ('admin', 'admin123!', '愿�由ъ옄', '010-0000-0000', 'admin@portflux.com', '愿�由ъ옄');

INSERT INTO ADMIN_ACCOUNT (user_num, admin_id, admin_password, admin_name)
SELECT user_num, 'admin', 'admin123!', '愿�由ъ옄'
FROM USERS WHERE user_id = 'admin';

-- 2) COMPANY (梨꾩슜怨듦퀬 �뜑誘몃뜲�씠�꽣�슜 湲곗뾽�쉶�썝 異붽�)
INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('naver', 'comp123!', '�꽕�씠踰�', '031-1234-5678', 'recruit@naver.com', '123-45-67890');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('kakaobank', 'comp123!', '移댁뭅�삤諭낇겕', '02-3333-5555', 'recruit@kakaobank.com', '123-45-67891');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('woowa', 'comp123!', '�슦�븘�븳�삎�젣�뱾', '1588-6060', 'recruit@woowa.com', '123-45-67892');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('samsung', 'comp123!', '�궪�꽦�쟾�옄', '031-200-1114', 'recruit@samsung.com', '123-45-67893');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('hyundai', 'comp123!', '�쁽���옄�룞李�', '02-3464-1114', 'recruit@hyundai.com', '123-45-67894');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('cjenm', 'comp123!', 'CJ ENM', '02-371-8500', 'recruit@cjenm.com', '123-45-67895');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('coupang', 'comp123!', '荑좏뙜', '1577-7011', 'recruit@coupang.com', '123-45-67896');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('lg', 'comp123!', 'LG�쟾�옄', '02-3777-1114', 'recruit@lg.com', '123-45-67897');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('amore', 'comp123!', '�븘紐⑤젅�띁�떆�뵿', '080-023-5454', 'recruit@amore.com', '123-45-67898');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('posco', 'comp123!', '�룷�뒪肄�', '054-220-0114', 'recruit@posco.com', '123-45-67899');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('skhynix', 'comp123!', 'SK�븯�씠�땳�뒪', '031-5179-0114', 'recruit@skhynix.com', '123-45-67800');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('samsunghospital', 'comp123!', '�궪�꽦�꽌�슱蹂묒썝', '02-3410-2114', 'recruit@samsunghosp.com', '123-45-67801');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('hanmi', 'comp123!', '�븳誘몄빟�뭹', '031-8059-8888', 'recruit@hanmi.com', '123-45-67802');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('shinhan', 'comp123!', '�떊�븳���뻾', '02-2151-0114', 'recruit@shinhan.com', '123-45-67803');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('toss', 'comp123!', '�넗�뒪', '1599-4905', 'recruit@toss.im', '123-45-67804');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('daekyo', 'comp123!', '��援�', '02-829-1000', 'recruit@daekyo.com', '123-45-67805');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('cjlogistics', 'comp123!', 'CJ���븳�넻�슫', '1588-1255', 'recruit@cjlogistics.com', '123-45-67806');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('samsungct', 'comp123!', '�궪�꽦臾쇱궛', '02-2145-3114', 'recruit@samsungct.com', '123-45-67807');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('paradise', 'comp123!', '�뙆�씪�떎�씠�뒪�샇�뀛', '051-742-2121', 'recruit@paradise.co.kr', '123-45-67808');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('starbucks', 'comp123!', '�뒪��踰낆뒪', '1522-3232', 'recruit@starbucks.co.kr', '123-45-67809');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('daangn', 'comp123!', '�떦洹쇰쭏耳�', '1661-8051', 'recruit@daangn.com', '123-45-67810');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('yanolja', 'comp123!', '�빞���옄', '1670-7829', 'recruit@yanolja.com', '123-45-67811');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('busanbank', 'comp123!', '遺��궛���뻾', '051-809-2000', 'recruit@busanbank.co.kr', '123-45-67812');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('dgbank', 'comp123!', '��援ъ��뻾', '053-756-2000', 'recruit@dgbank.co.kr', '123-45-67813');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('airport', 'comp123!', '�씤泥쒓났�빆怨듭궗', '032-741-2114', 'recruit@airport.kr', '123-45-67814');

-- 3) POST
-- �몮�윭蹂닿린 寃뚯떆湲��� lookup_Dummy_Data.sql�뿉�꽌 POST_ID 10-26�쑝濡� 愿�由�
-- 而ㅻ�ㅻ땲�떚(free) 寃뚯떆湲�: POST_ID 2000踰덈� �궗�슜
INSERT INTO POST (post_id, board_type, user_num, title, content, view_cnt)
VALUES (2001, 'free', 1, '�삤�씪�겢 DB �꽕移� 以� �뿉�윭 �빐寃� 諛⑸쾿',
        '�삤�씪�겢 19c �꽕移섑븯�떎媛� ORA-12154 �뿉�윭媛� 諛쒖깮�뻽�뼱�슂. �빐寃� 諛⑸쾿 怨듭쑀�빀�땲�떎.', 85);

INSERT INTO POST (post_id, board_type, user_num, title, content, view_cnt)
VALUES (2002, 'free', 2, 'Spring Boot �봽濡쒖젥�듃 援ъ“ 異붿쿇�빐二쇱꽭�슂',
        '泥섏쓬�쑝濡� Spring Boot濡� �겙 �봽濡쒖젥�듃瑜� �떆�옉�븯�뒗�뜲�슂. �뙣�궎吏� 援ъ“ 議곗뼵 遺��긽�뱶由쎈땲�떎.', 120);

-- 4) POST_COMMENT
-- �몮�윭蹂닿린 寃뚯떆湲�(post_id 10踰덈�)�뿉 ���븳 �뙎湲�
INSERT INTO POST_COMMENT (user_num, post_id, comment_content)
VALUES (2, 10, '�옄猷� �젙留� �쑀�씡�븯�꽕�슂! �떎�슫濡쒕뱶�빐�꽌 怨듬��븯寃좎뒿�땲�떎.');

INSERT INTO POST_COMMENT (user_num, post_id, comment_content)
VALUES (1, 10, '媛먯궗�빀�땲�떎! 留롮� �룄���씠 �릺�뀲�쑝硫� 醫뗪쿋�뼱�슂~');

-- 5) POST_SAVE
-- �몮�윭蹂닿린 寃뚯떆湲��뿉 ���븳 遺곷쭏�겕
INSERT INTO POST_SAVE (user_num, post_id) VALUES (1, 11);
INSERT INTO POST_SAVE (user_num, post_id) VALUES (2, 10);

-- 6) FOLLOWS
INSERT INTO FOLLOWS (follower_id, following_id) VALUES (1, 2);
INSERT INTO FOLLOWS (follower_id, following_id) VALUES (2, 1);

-- 7) DIRECT_CHAT_ROOMS
INSERT INTO DIRECT_CHAT_ROOMS (user1_num, user2_num, status) VALUES (1, 2, 'ACTIVE');

-- 8) CHAT_MESSAGES
INSERT INTO CHAT_MESSAGES (room_id, user_num, sender_num, content) VALUES (1, 2, 1, '�븞�뀞�븯�꽭�슂!');

-- 10) CART
-- �몮�윭蹂닿린 寃뚯떆湲��쓣 �옣諛붽뎄�땲�뿉 異붽�
INSERT INTO CART (user_num, post_id) VALUES (1, 10);
INSERT INTO CART (user_num, post_id) VALUES (2, 11);

-- 11) ORDERS
INSERT INTO ORDERS (user_id, merchant_uid, total_amount, status)
VALUES (1, 'ORD-20251230-001', 5500, 'PENDING');

-- 12) ORDER_ITEMS
-- �몮�윭蹂닿린 寃뚯떆湲� 援щℓ �궡�뿭
INSERT INTO ORDER_ITEMS (order_id, product_id, product_name, unit_price, qty)
VALUES (1, 10, '�쎒 �봽濡쒓렇�옒諛� �� �봽濡쒖젥�듃', 3500, 1);

INSERT INTO ORDER_ITEMS (order_id, product_id, product_name, unit_price, qty)
VALUES (1, 13, '�떖�뵆�븳 �쉶�깋 PPT', 2000, 1);

-- 13) POST_LIKE
-- �몮�윭蹂닿린 諛� 而ㅻ�ㅻ땲�떚 寃뚯떆湲��뿉 ���븳 醫뗭븘�슂
INSERT INTO POST_LIKE (user_num, post_id) VALUES (1, 10);
INSERT INTO POST_LIKE (user_num, post_id) VALUES (2, 10);
INSERT INTO POST_LIKE (user_num, post_id) VALUES (1, 2001);

-- 14) COMMENT_LIKE
INSERT INTO COMMENT_LIKE (user_num, comment_id) VALUES (2, 1);

-- ============================================================
-- 梨꾩슜怨듦퀬 �뜑誘� �뜲�씠�꽣 (�떎�젣 �꽌鍮꾩뒪 �떆�뿰�슜)
-- POST_ID 1000踰덈� �궗�슜�븯�뿬 �몮�윭蹂닿린/而ㅻ�ㅻ땲�떚�� 異⑸룎 諛⑹�
-- ============================================================

-- IT쨌媛쒕컻 遺꾩빞
INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1001, 'job', 1, '[�꽕�씠踰�] �떆�땲�뼱 諛깆뿏�뱶 媛쒕컻�옄 (Java/Spring)',
    '�꽕�씠踰� �겢�씪�슦�뱶�뿉�꽌 �떆�땲�뼱 諛깆뿏�뱶 媛쒕컻�옄瑜� 紐⑥쭛�빀�땲�떎. MSA �븘�궎�뀓泥� 寃쏀뿕�옄 �슦��. �옄�쑉 異쒗눜洹�, 媛꾩떇 臾댁젣�븳, 理쒖떊 �옣鍮� 吏��썝.',
    'gyeonggi_seongnam', '["寃쎈젰"]', '["5�뀈", "6�뀈", "7�뀈", "8�뀈", "9�뀈"]',
    'college_4', 'N',
    6000, 9000, SYSDATE + 30, 'ACTIVE',
    '["IT쨌�쎒쨌�넻�떊"]', '["��湲곗뾽"]', '["�젙洹쒖쭅"]', '["二� 5�씪(�썡~湲�)"]',
    1250, SYSDATE - 15, '031-1234-5678'
);

INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1002, 'job', 2, '[移댁뭅�삤諭낇겕] �봽濡좏듃�뿏�뱶 媛쒕컻�옄 (React/TypeScript)',
    '移댁뭅�삤諭낇겕 �쎒 �꽌鍮꾩뒪 �봽濡좏듃�뿏�뱶 媛쒕컻 �떞�떦. React, TypeScript �븘�닔. �꽦怨쇨툒, �뒪�넚�샃�뀡 �젣怨�.',
    'seoul_gangnam', '["寃쎈젰臾닿�", "�떊�엯"]', '[]',
    NULL, 'Y',
    4000, 7000, SYSDATE + 20, 'ACTIVE',
    '["IT쨌�쎒쨌�넻�떊", "湲덉쑖쨌蹂댄뿕"]', '["��湲곗뾽"]', '["�젙洹쒖쭅"]', '["二� 5�씪(�썡~湲�)"]',
    850, SYSDATE - 8, '02-3333-5555'
);

INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1003, 'job', 3, '[�슦�븘�븳�삎�젣�뱾] 紐⑤컮�씪 �빋 媛쒕컻�옄 (Android/iOS)',
    '諛곕떖�쓽誘쇱” 紐⑤컮�씪 �빋 媛쒕컻. Kotlin, Swift �슦��. �젏�떖/���뀅 �젣怨�, �옱�깮洹쇰Т 二� 2�쉶.',
    'seoul_songpa', '["寃쎈젰"]', '["3�뀈", "4�뀈", "5�뀈"]',
    'college_4', 'N',
    5000, 8000, SYSDATE + 25, 'ACTIVE',
    '["IT쨌�쎒쨌�넻�떊", "�꽌鍮꾩뒪�뾽"]', '["以묎껄湲곗뾽"]', '["�젙洹쒖쭅"]', '["二� 5�씪(�썡~湲�)"]',
    2150, SYSDATE - 3, '1588-6060'
);

-- �뵒�옄�씤 遺꾩빞
INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1004, 'job', 4, '[�궪�꽦�쟾�옄] UI/UX �뵒�옄�씠�꼫 (�떊�엯/寃쎈젰)',
    '�궪�꽦�쟾�옄 紐⑤컮�씪 �궗�뾽遺� UI/UX �뵒�옄�씠�꼫 梨꾩슜. Figma, Sketch �븘�닔. �빐�쇅 異쒖옣 湲고쉶 �젣怨�.',
    'gyeonggi_suwon', '["寃쎈젰臾닿�", "�떊�엯", "寃쎈젰"]', '["1�뀈", "2�뀈", "3�뀈"]',
    'college_4', 'N',
    4500, 6500, SYSDATE + 15, 'ACTIVE',
    '["IT쨌�쎒쨌�넻�떊", "�젣議걔룹깮�궛"]', '["��湲곗뾽"]', '["�젙洹쒖쭅"]', '["二� 5�씪(�썡~湲�)"]',
    620, SYSDATE - 12, '031-200-1114'
);

INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1005, 'job', 5, '[�쁽���옄�룞李�] �젣�뭹 �뵒�옄�씠�꼫 (Industrial Design)',
    '�쁽���옄�룞李� �뵒�옄�씤�꽱�꽣 �젣�뭹 �뵒�옄�씠�꼫. 3D 紐⑤뜽留� 寃쏀뿕 �븘�닔. �옄�룞李� �뵒�옄�씤 �룷�듃�뤃由ъ삤 �슦��.',
    'seoul_gangnam', '["寃쎈젰"]', '["3�뀈", "4�뀈", "5�뀈", "6�뀈"]',
    'college_4', 'N',
    5000, 7500, SYSDATE + 45, 'ACTIVE',
    '["�젣議걔룹깮�궛", "�옄�룞李㉱룹슫�넚"]', '["��湲곗뾽"]', '["�젙洹쒖쭅"]', '["二� 5�씪(�썡~湲�)"]',
    1580, SYSDATE - 5, '02-3464-1114'
);

-- 留덉��똿쨌湲고쉷 遺꾩빞
INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1006, 'job', 6, '[CJ ENM] 肄섑뀗痢� 留덉��꽣 (�떊�엯/寃쎈젰)',
    'CJ ENM �뵒吏��꽭 留덉��똿�� 梨꾩슜. SNS 留덉��똿 寃쏀뿕 �슦��. 而⑦뀗痢� �젣�옉 諛� 諛붿씠�윺 留덉��똿 �떞�떦.',
    'seoul_mapo', '["寃쎈젰臾닿�", "�떊�엯"]', '[]',
    NULL, 'Y',
    3500, 5500, SYSDATE + 18, 'ACTIVE',
    '["誘몃뵒�뼱쨌愿묎퀬", "�뿏�꽣�뀒�씤癒쇳듃"]', '["��湲곗뾽"]', '["�젙洹쒖쭅"]', '["二� 5�씪(�썡~湲�)"]',
    420, SYSDATE - 22, '02-371-8500'
);

INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1007, 'job', 7, '[荑좏뙜] �긽�뭹 湲고쉷�옄 (PM)',
    '荑좏뙜 �씠而ㅻ㉧�뒪 �긽�뭹 湲고쉷. �뜲�씠�꽣 遺꾩꽍 �뒫�젰 �븘�닔. AWS, SQL �솢�슜 寃쏀뿕 �슦��.',
    'seoul_songpa', '["寃쎈젰"]', '["2�뀈", "3�뀈", "4�뀈"]',
    'college_4', 'N',
    4500, 7000, SYSDATE + 22, 'ACTIVE',
    '["IT쨌�쎒쨌�넻�떊", "�쑀�넻쨌臾댁뿭"]', '["��湲곗뾽"]', '["�젙洹쒖쭅"]', '["二� 5�씪(�썡~湲�)"]',
    980, SYSDATE - 7, '1577-7011'
);

-- �쁺�뾽쨌�뙋留� 遺꾩빞
INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1008, 'job', 8, '[LG�쟾�옄] B2B �쁺�뾽 �떞�떦�옄',
    'LG�쟾�옄 湲곗뾽 �쁺�뾽�� 梨꾩슜. 踰뺤씤 �쁺�뾽 寃쏀뿕 �슦��. �씤�꽱�떚釉� 蹂꾨룄 吏�湲�, �쁺�뾽李⑤웾 �젣怨�.',
    'seoul_yeongdeungpo', '["寃쎈젰"]', '["3�뀈", "4�뀈", "5�뀈"]',
    'college_2_3', 'N',
    4000, 6000, SYSDATE + 50, 'ACTIVE',
    '["�젣議걔룹깮�궛", "�쁺�뾽쨌�뙋留�"]', '["��湲곗뾽"]', '["�젙洹쒖쭅"]', '["二� 5�씪(�썡~湲�)"]',
    750, SYSDATE - 18, '02-3777-1114'
);

INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1009, 'job', 9, '[�븘紐⑤젅�띁�떆�뵿] 酉고떚 而⑥꽕�꽩�듃',
    '�븘紐⑤젅�띁�떆�뵿 硫댁꽭�젏 酉고떚 而⑥꽕�꽩�듃. �쇅援��뼱 �뒫�젰 �슦��. 紐낇뭹 釉뚮옖�뱶 寃쏀뿕 �솚�쁺.',
    'seoul_jung', '["寃쎈젰臾닿�"]', '[]',
    NULL, 'Y',
    2800, 4500, SYSDATE + 30, 'ACTIVE',
    '["�솕�옣�뭹쨌酉고떚", "�쑀�넻쨌臾댁뿭"]', '["��湲곗뾽"]', '["�젙洹쒖쭅"]', '["二� 5�씪(�썡~湲�)", "二� 6�씪"]',
    320, SYSDATE - 26, '080-023-5454'
);

-- �젣議걔룹깮�궛 遺꾩빞
INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1010, 'job', 10, '[�룷�뒪肄�] �깮�궛愿�由� �뿏吏��땲�뼱',
    '�룷�뒪肄� �젣泥좎냼 �깮�궛愿�由�. 怨듭젙 理쒖쟻�솕 諛� �뭹吏덇�由� �떞�떦. 湲곗닕�궗 �젣怨�, 3援먮� 洹쇰Т.',
    'gyeongbuk_pohang', '["寃쎈젰"]', '["5�뀈", "6�뀈", "7�뀈"]',
    'college_4', 'N',
    5500, 8000, SYSDATE + 20, 'ACTIVE',
    '["�젣議걔룹깮�궛", "泥좉컯쨌湲덉냽"]', '["��湲곗뾽"]', '["�젙洹쒖쭅"]', '["援먮�洹쇰Т"]',
    1420, SYSDATE - 9, '054-220-0114'
);

INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1011, 'job', 11, '[SK�븯�씠�땳�뒪] 諛섎룄泥� 怨듭젙 �뿏吏��땲�뼱',
    'SK�븯�씠�땳�뒪 諛섎룄泥� 怨듭젙 �뿏吏��땲�뼱. �쟾怨듭옄 �슦��. �뀛��踰꾩뒪 �슫�쁺, 以묒떇 �젣怨�.',
    'gyeonggi_icheon', '["寃쎈젰臾닿�", "�떊�엯"]', '[]',
    NULL, 'Y',
    4500, 6500, SYSDATE + 25, 'ACTIVE',
    '["IT쨌�쎒쨌�넻�떊", "�젣議걔룹깮�궛"]', '["��湲곗뾽"]', '["�젙洹쒖쭅"]', '["援먮�洹쇰Т"]',
    1890, SYSDATE - 2, '031-5179-0114'
);

-- �쓽猷뙿룹젣�빟 遺꾩빞
INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1012, 'job', 12, '[�궪�꽦�꽌�슱蹂묒썝] 媛꾪샇�궗 (�떊洹� 梨꾩슜)',
    '�궪�꽦�꽌�슱蹂묒썝 媛꾪샇�궗 �떊洹� 梨꾩슜. 媛꾪샇�궗 硫댄뿀 �븘�닔. 3援먮� 媛��뒫�옄. 湲곗닕�궗 諛� �븰�옄湲� 吏��썝.',
    'seoul_gangnam', '["寃쎈젰臾닿�", "�떊�엯"]', '[]',
    NULL, 'Y',
    3800, 5500, SYSDATE + 55, 'ACTIVE',
    '["�쓽猷뙿룹젣�빟쨌蹂듭�"]', '["��湲곗뾽"]', '["�젙洹쒖쭅"]', '["援먮�洹쇰Т"]',
    540, SYSDATE - 14, '02-3410-2114'
);

INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1013, 'job', 13, '[�븳誘몄빟�뭹] �엫�긽�뿰援ъ썝 (CRA)',
    '�븳誘몄빟�뭹 �엫�긽�뿰援ъ썝 梨꾩슜. �빟�븰, 媛꾪샇�븰 �쟾怨듭옄 �슦��. 援��궡�쇅 �엫�긽�떆�뿕 紐⑤땲�꽣留� �떞�떦.',
    'gyeonggi_hwaseong', '["寃쎈젰"]', '["2�뀈", "3�뀈", "4�뀈"]',
    'college_4', 'N',
    4000, 6000, SYSDATE + 18, 'ACTIVE',
    '["�쓽猷뙿룹젣�빟쨌蹂듭�"]', '["以묎껄湲곗뾽"]', '["�젙洹쒖쭅"]', '["二� 5�씪(�썡~湲�)"]',
    280, SYSDATE - 21, '031-8059-8888'
);

-- 湲덉쑖 遺꾩빞
INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1014, 'job', 14, '[�떊�븳���뻾] �뵒吏��꽭 湲덉쑖 �쟾臾멸�',
    '�떊�븳���뻾 �뵒吏��꽭湲덉쑖遺� 梨꾩슜. ���뀒�겕 寃쏀뿕�옄 �슦��. 紐⑤컮�씪諭낇궧 �꽌鍮꾩뒪 湲고쉷 諛� �슫�쁺.',
    'seoul_jung', '["寃쎈젰"]', '["3�뀈", "4�뀈", "5�뀈", "6�뀈"]',
    'college_4', 'N',
    5000, 7500, SYSDATE + 20, 'ACTIVE',
    '["湲덉쑖쨌蹂댄뿕"]', '["��湲곗뾽"]', '["�젙洹쒖쭅"]', '["二� 5�씪(�썡~湲�)"]',
    1120, SYSDATE - 6, '02-2151-0114'
);

INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1015, 'job', 15, '[�넗�뒪] �뜲�씠�꽣 遺꾩꽍媛� (Data Analyst)',
    '�넗�뒪 �뜲�씠�꽣�� 遺꾩꽍媛� 梨꾩슜. Python, SQL �븘�닔. 湲덉쑖 �뜲�씠�꽣 遺꾩꽍 諛� �씤�궗�씠�듃 �룄異�.',
    'seoul_gangnam', '["寃쎈젰臾닿�", "�떊�엯", "寃쎈젰"]', '["1�뀈", "2�뀈", "3�뀈"]',
    'college_4', 'N',
    4500, 7000, SYSDATE + 25, 'ACTIVE',
    '["湲덉쑖쨌蹂댄뿕", "IT쨌�쎒쨌�넻�떊"]', '["以묎껄湲곗뾽"]', '["�젙洹쒖쭅"]', '["二� 5�씪(�썡~湲�)"]',
    2380, SYSDATE - 1, '1599-4905'
);

-- 援먯쑁 遺꾩빞
INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1016, 'job', 16, '[��援�] 援먯쑁 肄섑뀗痢� 媛쒕컻�옄',
    '��援� �뵒吏��꽭 援먯쑁 肄섑뀗痢� 媛쒕컻. 援먯쑁�븰, �떖由ы븰 �쟾怨듭옄 �슦��. 珥덉쨷�벑 援먯옱 媛쒕컻 �떞�떦.',
    'seoul_gangnam', '["寃쎈젰"]', '["2�뀈", "3�뀈", "4�뀈"]',
    'college_4', 'N',
    3500, 5000, SYSDATE + 60, 'ACTIVE',
    '["援먯쑁쨌�븰�썝"]', '["以묎껄湲곗뾽"]', '["�젙洹쒖쭅"]', '["二� 5�씪(�썡~湲�)"]',
    195, SYSDATE - 28, '02-829-1000'
);

-- 臾쇰쪟쨌�슫�넚 遺꾩빞
INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1017, 'job', 17, '[CJ���븳�넻�슫] 臾쇰쪟 愿�由ъ옄',
    'CJ���븳�넻�슫 臾쇰쪟�꽱�꽣 愿�由ъ옄. WMS �떆�뒪�뀥 寃쏀뿕 �슦��. �옱怨좉�由� 諛� 諛곗넚 理쒖쟻�솕 �떞�떦.',
    'gyeonggi_yongin', '["寃쎈젰"]', '["3�뀈", "4�뀈", "5�뀈"]',
    'college_2_3', 'N',
    3800, 5500, SYSDATE + 65, 'ACTIVE',
    '["臾쇰쪟쨌�슫�넚"]', '["��湲곗뾽"]', '["�젙洹쒖쭅"]', '["二� 5�씪(�썡~湲�)"]',
    890, SYSDATE - 11, '1588-1255'
);

-- 嫄댁꽕쨌嫄댁텞 遺꾩빞
INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1018, 'job', 18, '[�궪�꽦臾쇱궛] 嫄댁텞 �쁽�옣 �냼�옣',
    '�궪�꽦臾쇱궛 嫄댁꽕遺�臾� �쁽�옣�냼�옣. 嫄댁텞�떆怨듦린�닠�궗 �슦��. ���삎 �븘�뙆�듃 �쁽�옣 愿�由�.',
    'gyeonggi_gwangmyeong', '["寃쎈젰"]', '["10�뀈 �씠�긽"]',
    'college_4', 'N',
    6500, 10000, SYSDATE + 30, 'ACTIVE',
    '["嫄댁꽕쨌嫄댁텞"]', '["��湲곗뾽"]', '["�젙洹쒖쭅"]', '["二� 6�씪"]',
    370, SYSDATE - 24, '02-2145-3114'
);

-- �샇�뀛쨌愿�愿� 遺꾩빞
INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1019, 'job', 19, '[�뙆�씪�떎�씠�뒪�샇�뀛] �봽�윴�듃 �뜲�뒪�겕 (�떊�엯)',
    '�뙆�씪�떎�씠�뒪�샇�뀛 遺��궛 �봽�윴�듃 �뜲�뒪�겕 �떊�엯 梨꾩슜. �쁺�뼱/以묎뎅�뼱 媛��뒫�옄 �슦��. 援먮�洹쇰Т.',
    'busan_haeundae', '["寃쎈젰臾닿�", "�떊�엯"]', '[]',
    NULL, 'Y',
    2800, 3800, SYSDATE + 20, 'ACTIVE',
    '["�샇�뀛쨌愿�愿뫢룹뿬媛�"]', '["以묎껄湲곗뾽"]', '["�젙洹쒖쭅"]', '["援먮�洹쇰Т"]',
    650, SYSDATE - 10, '051-742-2121'
);

-- �쇅�떇쨌�떇�쓬猷� 遺꾩빞
INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1020, 'job', 20, '[�뒪��踰낆뒪] 留ㅼ옣 留ㅻ땲�� (�젏�옣 �썑蹂�)',
    '�뒪��踰낆뒪 留ㅼ옣 留ㅻ땲�� 梨꾩슜. 移댄럹 �슫�쁺 寃쏀뿕 3�뀈 �씠�긽. 留ㅼ텧 愿�由� 諛� �씤�젰 �슫�쁺 �떞�떦.',
    'seoul_gangnam', '["寃쎈젰"]', '["3�뀈", "4�뀈", "5�뀈"]',
    'high', 'N',
    3200, 4500, SYSDATE + 15, 'ACTIVE',
    '["�쇅�떇쨌�떇�쓬猷�"]', '["��湲곗뾽"]', '["�젙洹쒖쭅"]', '["二� 5�씪(�썡~湲�)"]',
    480, SYSDATE - 16, '1522-3232'
);

-- �뒪���듃�뾽 (�떊�엯 �슦��)
INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1021, 'job', 21, '[�떦洹쇰쭏耳�] ���뒪�깮 媛쒕컻�옄 (二쇰땲�뼱)',
    '�떦洹쇰쭏耳� ���뒪�깮 媛쒕컻�옄 梨꾩슜. React, Node.js 寃쏀뿕�옄. �뒪�넚�샃�뀡 �젣怨�, �옄�쑉異쒗눜洹�.',
    'seoul_gangnam', '["寃쎈젰臾닿�", "�떊�엯", "寃쎈젰"]', '["1�뀈", "2�뀈"]',
    NULL, 'Y',
    4000, 6000, SYSDATE + 25, 'ACTIVE',
    '["IT쨌�쎒쨌�넻�떊"]', '["�뒪���듃�뾽"]', '["�젙洹쒖쭅"]', '["二� 5�씪(�썡~湲�)"]',
    1750, SYSDATE - 4, '1661-8051'
);

INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1022, 'job', 22, '[�빞���옄] �꽌鍮꾩뒪 湲고쉷�옄 (PM)',
    '�빞���옄 �꽌鍮꾩뒪 湲고쉷 �떞�떦. �뿬�뻾/�닕諛� �꽌鍮꾩뒪 湲고쉷 寃쏀뿕 �슦��. �쑀�뿰洹쇰Т�젣.',
    'seoul_gangnam', '["寃쎈젰"]', '["2�뀈", "3�뀈", "4�뀈"]',
    'college_4', 'N',
    4200, 6500, SYSDATE + 18, 'ACTIVE',
    '["IT쨌�쎒쨌�넻�떊", "�샇�뀛쨌愿�愿뫢룹뿬媛�"]', '["以묎껄湲곗뾽"]', '["�젙洹쒖쭅"]', '["二� 5�씪(�썡~湲�)"]',
    1060, SYSDATE - 13, '1670-7829'
);

-- 吏�諛� 吏��뿭 梨꾩슜怨듦퀬
INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1023, 'job', 23, '[遺��궛���뻾] 李쎄뎄 �뀛�윭 (�떊�엯)',
    '遺��궛���뻾 �쁺�뾽�젏 李쎄뎄 �뀛�윭 梨꾩슜. 湲덉쑖沅� 寃쏀뿕 �슦��. �젙洹쒖쭅 �쟾�솚 媛��뒫.',
    'busan_busanjin', '["寃쎈젰臾닿�", "�떊�엯"]', '[]',
    NULL, 'Y',
    2800, 3500, SYSDATE + 20, 'ACTIVE',
    '["湲덉쑖쨌蹂댄뿕"]', '["以묎껄湲곗뾽"]', '["�젙洹쒖쭅"]', '["二� 5�씪(�썡~湲�)"]',
    340, SYSDATE - 19, '051-809-2000'
);

INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1024, 'job', 24, '[��援ъ��뻾] 媛쒖씤�쁺�뾽 �떞�떦�옄',
    '��援ъ��뻾 PB�꽱�꽣 媛쒖씤�쁺�뾽 �떞�떦. 湲덉쑖�긽�뭹 �뙋留� 諛� �옄�궛愿�由�. �씤�꽱�떚釉� 蹂꾨룄.',
    'daegu_jung', '["寃쎈젰"]', '["2�뀈", "3�뀈", "4�뀈"]',
    'college_2_3', 'N',
    3200, 5000, SYSDATE + 25, 'ACTIVE',
    '["湲덉쑖쨌蹂댄뿕"]', '["以묎껄湲곗뾽"]', '["�젙洹쒖쭅"]', '["二� 5�씪(�썡~湲�)"]',
    510, SYSDATE - 17, '053-756-2000'
);

INSERT INTO POST (
    post_id, board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days,
    view_cnt, created_at, company_phone
) VALUES (
    1025, 'job', 25, '[�씤泥쒓났�빆怨듭궗] �떆�꽕愿�由� 吏곸썝',
    '�씤泥쒓뎅�젣怨듯빆 �떆�꽕愿�由ы�. �쟾湲�/湲곌퀎 �옄寃⑹쬆 �냼吏��옄 �슦��. 3援먮� 洹쇰Т.',
    'incheon_jung', '["寃쎈젰"]', '["3�뀈", "4�뀈", "5�뀈"]',
    'college_2_3', 'N',
    3800, 5500, SYSDATE + 70, 'ACTIVE',
    '["嫄댁꽕쨌嫄댁텞", "怨듦났湲곌�"]', '["怨듦린�뾽"]', '["�젙洹쒖쭅"]', '["援먮�洹쇰Т"]',
    770, SYSDATE - 20, '032-741-2114'
);

COMMIT;

-- ============================================================
-- �뜲�씠�꽣 �솗�씤
-- ============================================================

SELECT 'USERS' AS �뀒�씠釉붾챸, COUNT(*) AS �뜲�씠�꽣媛쒖닔 FROM USERS
UNION ALL
SELECT 'COMPANY', COUNT(*) FROM COMPANY
UNION ALL
SELECT 'POST', COUNT(*) FROM POST
UNION ALL
SELECT 'POST_COMMENT', COUNT(*) FROM POST_COMMENT
UNION ALL
SELECT 'POST_SAVE', COUNT(*) FROM POST_SAVE
UNION ALL
SELECT 'FOLLOWS', COUNT(*) FROM FOLLOWS
UNION ALL
SELECT 'DIRECT_CHAT_ROOMS', COUNT(*) FROM DIRECT_CHAT_ROOMS
UNION ALL
SELECT 'CHAT_MESSAGES', COUNT(*) FROM CHAT_MESSAGES
UNION ALL
SELECT 'CHAT_MESSAGE_FILES', COUNT(*) FROM CHAT_MESSAGE_FILES
UNION ALL
SELECT 'CART', COUNT(*) FROM CART
UNION ALL
SELECT 'ORDERS', COUNT(*) FROM ORDERS
UNION ALL
SELECT 'ORDER_ITEMS', COUNT(*) FROM ORDER_ITEMS
UNION ALL
SELECT 'POST_LIKE', COUNT(*) FROM POST_LIKE
UNION ALL
SELECT 'COMMENT_LIKE', COUNT(*) FROM COMMENT_LIKE
UNION ALL
SELECT 'PAYMENTS', COUNT(*) FROM PAYMENTS
UNION ALL
SELECT 'PAY', COUNT(*) FROM PAY;

-- ============================================================
-- 異붽� 而щ읆 (湲곗〈 �뀒�씠釉� �닔�젙)
-- ============================================================

-- POST �뀒�씠釉붿뿉 COMPANY_LOGO 而щ읆 異붽�
-- �씠誘� 而щ읆�씠 �엳�쑝硫� �뿉�윭媛� 諛쒖깮�븯誘�濡�, �븘�슂�떆 二쇱꽍 泥섎━�븯�꽭�슂
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE POST ADD (COMPANY_LOGO CLOB)';
    DBMS_OUTPUT.PUT_LINE('COMPANY_LOGO 而щ읆�씠 異붽��릺�뿀�뒿�땲�떎.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('COMPANY_LOGO 而щ읆�씠 �씠誘� 議댁옱�빀�땲�떎.');
        ELSE
            RAISE;
        END IF;
END;
/

-- POST �뀒�씠釉붿뿉 COMPANY_PHONE 而щ읆 異붽�
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE POST ADD (COMPANY_PHONE VARCHAR2(20))';
    DBMS_OUTPUT.PUT_LINE('COMPANY_PHONE 而щ읆�씠 異붽��릺�뿀�뒿�땲�떎.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('COMPANY_PHONE 而щ읆�씠 �씠誘� 議댁옱�빀�땲�떎.');
        ELSEs
            RAISE;
        END IF;
END;
/

COMMIT;