-- ============================================================
-- Part 1: 테이블 생성 스크립트 (ORDERS, ORDER_ITEMS, PAYMENTS 포함)
-- ============================================================

-- 기존 테이블 삭제 (있을 경우)
DROP TABLE PAYMENTS CASCADE CONSTRAINTS;
DROP TABLE ORDER_ITEMS CASCADE CONSTRAINTS;
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE CART CASCADE CONSTRAINTS;
DROP TABLE COMMENT_LIKE CASCADE CONSTRAINTS;
DROP TABLE POST_LIKE CASCADE CONSTRAINTS;
DROP TABLE CHAT_MESSAGE_FILES CASCADE CONSTRAINTS;
DROP TABLE CHAT_MESSAGES CASCADE CONSTRAINTS;
DROP TABLE DIRECT_CHAT_ROOMS CASCADE CONSTRAINTS;
DROP TABLE FOLLOWS CASCADE CONSTRAINTS;
DROP TABLE POST_SAVE CASCADE CONSTRAINTS;
DROP TABLE POST_COMMENT CASCADE CONSTRAINTS;
DROP TABLE POST CASCADE CONSTRAINTS;
DROP TABLE COMPANY CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;

------------------------------------------------------------
-- 1) USERS
------------------------------------------------------------
CREATE TABLE USERS (
    user_num NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR2(50) NOT NULL,
    user_password VARCHAR2(100) NOT NULL,
    user_name VARCHAR2(100) NOT NULL,
    user_phone VARCHAR2(20),
    user_email VARCHAR2(255) NOT NULL,
    user_nickname VARCHAR2(100) NOT NULL,
    drawn_user CHAR(1) DEFAULT 'N',
    user_create_at DATE DEFAULT SYSDATE NOT NULL,
    user_level NUMBER(2),
    user_image BLOB,
    user_banner BLOB
);

------------------------------------------------------------
-- 2) COMPANY
------------------------------------------------------------
CREATE TABLE COMPANY (
    company_num NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id VARCHAR2(50) NOT NULL,
    company_password VARCHAR2(100) NOT NULL,
    company_name VARCHAR2(100) NOT NULL,
    company_phone VARCHAR2(20) NOT NULL,
    company_email VARCHAR2(255) NOT NULL,
    drawn_company CHAR(1) DEFAULT 'N',
    company_create_at DATE DEFAULT SYSDATE,
    company_image BLOB,
    company_banner BLOB,
    business_number VARCHAR2(20) NOT NULL
);

------------------------------------------------------------
-- 3) POST
------------------------------------------------------------
CREATE TABLE POST (
    post_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_type VARCHAR2(10) NOT NULL,
    CONSTRAINT ck_post_board_type CHECK (board_type IN ('lookup', 'job', 'free')),
    user_num NUMBER(20),
    company_num NUMBER(20),
    title VARCHAR2(255) NOT NULL,
    content VARCHAR2(4000) NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE DEFAULT SYSDATE NOT NULL,
    view_cnt NUMBER DEFAULT 0,
    price NUMBER(10),
    ai_summary VARCHAR2(500),
    download_cnt NUMBER DEFAULT 0,
    post_file VARCHAR2(255),
    CONSTRAINT ck_lookup_user CHECK (
        (board_type = 'lookup' AND price IS NOT NULL AND ai_summary IS NOT NULL AND download_cnt IS NOT NULL AND post_file IS NOT NULL)
        OR board_type IN ('job', 'free')
    ),
    CONSTRAINT ck_job_company CHECK (
        (board_type = 'job' AND company_num IS NOT NULL)
        OR board_type IN ('lookup', 'free')
    ),
    CONSTRAINT ck_free_user CHECK (
        ((board_type = 'free' OR board_type = 'lookup') AND user_num IS NOT NULL)
        OR board_type = 'job'
    )
);

-- POST updated_at 트리거
CREATE OR REPLACE TRIGGER trg_post_update
BEFORE UPDATE ON POST
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;
/

-- POST tags 컬럼 추가
ALTER TABLE POST ADD tags VARCHAR2(2000);

-- POST 외래키
ALTER TABLE POST ADD CONSTRAINT fk_post_user FOREIGN KEY (user_num) REFERENCES USERS(user_num);
ALTER TABLE POST ADD CONSTRAINT fk_post_company FOREIGN KEY (company_num) REFERENCES COMPANY(company_num);

-- POST 인덱스
CREATE INDEX idx_post_tags ON POST(tags);

------------------------------------------------------------
-- 4) POST_COMMENT
------------------------------------------------------------
CREATE TABLE POST_COMMENT (
    comment_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_num NUMBER(20) NOT NULL,
    post_id NUMBER(20) NOT NULL,
    comment_content VARCHAR2(1000),
    comment_created_at DATE DEFAULT SYSDATE,
    comment_modify_at DATE
);

ALTER TABLE POST_COMMENT ADD CONSTRAINT fk_comment_user FOREIGN KEY (user_num) REFERENCES USERS(user_num);
ALTER TABLE POST_COMMENT ADD CONSTRAINT fk_comment_post FOREIGN KEY (post_id) REFERENCES POST(post_id);

------------------------------------------------------------
-- 5) POST_SAVE
------------------------------------------------------------
CREATE TABLE POST_SAVE (
    board_save_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_save_time DATE DEFAULT SYSDATE NOT NULL,
    user_num NUMBER(20) NOT NULL,
    post_id NUMBER(20) NOT NULL
);

ALTER TABLE POST_SAVE ADD CONSTRAINT fk_save_user FOREIGN KEY (user_num) REFERENCES USERS(user_num);
ALTER TABLE POST_SAVE ADD CONSTRAINT fk_save_post FOREIGN KEY (post_id) REFERENCES POST(post_id);

------------------------------------------------------------
-- 6) FOLLOWS
------------------------------------------------------------
CREATE TABLE FOLLOWS (
    follow_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id NUMBER(20) NOT NULL,
    following_id NUMBER(20) NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE FOLLOWS ADD CONSTRAINT fk_follows_follower FOREIGN KEY (follower_id) REFERENCES USERS(user_num);
ALTER TABLE FOLLOWS ADD CONSTRAINT fk_follows_following FOREIGN KEY (following_id) REFERENCES USERS(user_num);

------------------------------------------------------------
-- 7) DIRECT_CHAT_ROOMS
------------------------------------------------------------
CREATE TABLE DIRECT_CHAT_ROOMS (
    room_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user1_num NUMBER(20) NOT NULL,
    user2_num NUMBER(20) NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    last_message_at DATE,
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
);

ALTER TABLE DIRECT_CHAT_ROOMS ADD CONSTRAINT fk_chatroom_user1 FOREIGN KEY (user1_num) REFERENCES USERS(user_num);
ALTER TABLE DIRECT_CHAT_ROOMS ADD CONSTRAINT fk_chatroom_user2 FOREIGN KEY (user2_num) REFERENCES USERS(user_num);

------------------------------------------------------------
-- 8) CHAT_MESSAGES
------------------------------------------------------------
CREATE TABLE CHAT_MESSAGES (
    message_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id NUMBER(20) NOT NULL,
    user_num NUMBER(20) NOT NULL,
    sender_num NUMBER(20) NOT NULL,
    content VARCHAR2(2000),
    has_file CHAR(1) DEFAULT 'N' NOT NULL,
    sent_at DATE DEFAULT SYSDATE NOT NULL,
    read_yn CHAR(1) DEFAULT 'N' NOT NULL,
    deleted_yn CHAR(1) DEFAULT 'N' NOT NULL
);

ALTER TABLE CHAT_MESSAGES ADD CONSTRAINT fk_message_room FOREIGN KEY (room_id) REFERENCES DIRECT_CHAT_ROOMS(room_id);
ALTER TABLE CHAT_MESSAGES ADD CONSTRAINT fk_message_user FOREIGN KEY (user_num) REFERENCES USERS(user_num);
ALTER TABLE CHAT_MESSAGES ADD CONSTRAINT fk_message_sender FOREIGN KEY (sender_num) REFERENCES USERS(user_num);

------------------------------------------------------------
-- 9) CHAT_MESSAGE_FILES
------------------------------------------------------------
CREATE TABLE CHAT_MESSAGE_FILES (
    file_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id NUMBER(20) NOT NULL,
    file_name VARCHAR2(255) NOT NULL,
    mime_type VARCHAR2(100),
    file_size NUMBER(20),
    file_path VARCHAR2(1000),
    file_data BLOB,
    uploaded_at DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE CHAT_MESSAGE_FILES ADD CONSTRAINT fk_file_message FOREIGN KEY (message_id) REFERENCES CHAT_MESSAGES(message_id);

------------------------------------------------------------
-- 10) CART
------------------------------------------------------------
CREATE TABLE CART (
    cart_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_num NUMBER(20) NOT NULL,
    post_id NUMBER(20) NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE CART ADD CONSTRAINT fk_cart_user FOREIGN KEY (user_num) REFERENCES USERS(user_num);
ALTER TABLE CART ADD CONSTRAINT fk_cart_post FOREIGN KEY (post_id) REFERENCES POST(post_id);

------------------------------------------------------------
-- 11) ORDERS (주문 내역)
------------------------------------------------------------
CREATE TABLE ORDERS (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id NUMBER(20) NOT NULL,
    merchant_uid VARCHAR2(255) NOT NULL,
    total_amount NUMBER(19,2) NOT NULL,
    status VARCHAR2(50) NOT NULL,
    imp_uid VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_orders_merchant_uid UNIQUE (merchant_uid)
);

ALTER TABLE ORDERS ADD CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES USERS(user_num);

CREATE INDEX idx_orders_merchant_uid ON ORDERS(merchant_uid);
CREATE INDEX idx_orders_user_id ON ORDERS(user_id);
CREATE INDEX idx_orders_created_at ON ORDERS(created_at);

COMMENT ON TABLE ORDERS IS '주문 내역 관리 테이블';
COMMENT ON COLUMN ORDERS.merchant_uid IS '주문 고유 식별자 (UUID 기반)';
COMMENT ON COLUMN ORDERS.status IS '주문 상태 (CREATED, PENDING, PAID, CANCELLED)';

------------------------------------------------------------
-- 12) ORDER_ITEMS (주문 상품 상세)
------------------------------------------------------------
CREATE TABLE ORDER_ITEMS (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    product_id NUMBER(20) NOT NULL,
    product_name VARCHAR2(500) NOT NULL,
    unit_price NUMBER(19,2) NOT NULL,
    qty NUMBER NOT NULL
);

ALTER TABLE ORDER_ITEMS ADD CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES ORDERS(id) ON DELETE CASCADE;
ALTER TABLE ORDER_ITEMS ADD CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES POST(post_id);

CREATE INDEX idx_order_items_order_id ON ORDER_ITEMS(order_id);
CREATE INDEX idx_order_items_product_id ON ORDER_ITEMS(product_id);

COMMENT ON TABLE ORDER_ITEMS IS '주문 상품 상세 정보';
COMMENT ON COLUMN ORDER_ITEMS.qty IS '주문 수량';

------------------------------------------------------------
-- 13) POST_LIKE (게시글 좋아요)
------------------------------------------------------------
CREATE TABLE POST_LIKE (
    like_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_num NUMBER(20) NOT NULL,
    post_id NUMBER(20) NOT NULL,
    liked_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uq_post_like UNIQUE (user_num, post_id)
);

ALTER TABLE POST_LIKE ADD CONSTRAINT fk_postlike_user FOREIGN KEY (user_num) REFERENCES USERS(user_num);
ALTER TABLE POST_LIKE ADD CONSTRAINT fk_postlike_post FOREIGN KEY (post_id) REFERENCES POST(post_id);

------------------------------------------------------------
-- 14) COMMENT_LIKE (댓글 좋아요)
------------------------------------------------------------
CREATE TABLE COMMENT_LIKE (
    like_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_num NUMBER(20) NOT NULL,
    comment_id NUMBER(20) NOT NULL,
    liked_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uq_comment_like UNIQUE (user_num, comment_id)
);

ALTER TABLE COMMENT_LIKE ADD CONSTRAINT fk_commentlike_user FOREIGN KEY (user_num) REFERENCES USERS(user_num);
ALTER TABLE COMMENT_LIKE ADD CONSTRAINT fk_commentlike_comment FOREIGN KEY (comment_id) REFERENCES POST_COMMENT(comment_id);

------------------------------------------------------------
-- 15) PAYMENTS (결제 기록)
------------------------------------------------------------
CREATE TABLE PAYMENTS (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    imp_uid VARCHAR2(255) NOT NULL,
    merchant_uid VARCHAR2(255) NOT NULL,
    amount NUMBER(19,2) NOT NULL,
    status VARCHAR2(50) NOT NULL,
    paid_at TIMESTAMP,
    raw_response CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_payments_imp_uid UNIQUE (imp_uid),
    CONSTRAINT uq_payments_merchant_uid UNIQUE (merchant_uid)
);

ALTER TABLE PAYMENTS ADD CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES ORDERS(id) ON DELETE CASCADE;

CREATE INDEX idx_payments_order_id ON PAYMENTS(order_id);
CREATE INDEX idx_payments_merchant_uid ON PAYMENTS(merchant_uid);
CREATE INDEX idx_payments_imp_uid ON PAYMENTS(imp_uid);
CREATE INDEX idx_payments_status ON PAYMENTS(status);

COMMENT ON TABLE PAYMENTS IS '결제 기록 관리 테이블 (아임포트 연동)';
COMMENT ON COLUMN PAYMENTS.imp_uid IS '아임포트 거래 고유 ID';
COMMENT ON COLUMN PAYMENTS.merchant_uid IS '가맹점 주문 번호 (ORDERS.merchant_uid)';
COMMENT ON COLUMN PAYMENTS.status IS '결제 상태 (READY, PAID, CANCELLED, REFUNDED)';
COMMENT ON COLUMN PAYMENTS.raw_response IS '아임포트 응답 원본 데이터 (JSON)';

-- 채용공고 관련 컬럼 추가
ALTER TABLE POST ADD (
    job_region VARCHAR2(100),
    job_career_type VARCHAR2(500),
    job_career_years VARCHAR2(500),
    job_education VARCHAR2(50),
    job_education_exclude CHAR(1) DEFAULT 'N',
    job_salary_min NUMBER(10),
    job_salary_max NUMBER(10),
    job_deadline DATE,
    job_status VARCHAR2(20) DEFAULT 'ACTIVE',
    job_industries VARCHAR2(500),
    job_company_types VARCHAR2(500),
    job_work_types VARCHAR2(500),
    job_work_days VARCHAR2(500)
);

-- 채용공고 제약조건
ALTER TABLE POST ADD CONSTRAINT ck_job_required_fields CHECK (
    (board_type = 'job' AND job_region IS NOT NULL AND job_deadline IS NOT NULL AND job_status IS NOT NULL)
    OR board_type IN ('lookup', 'free')
);

ALTER TABLE POST ADD CONSTRAINT ck_job_status CHECK (
    job_status IN ('ACTIVE', 'EXPIRED', 'CLOSED') OR job_status IS NULL
);

-- 채용공고 인덱스
CREATE INDEX idx_post_job_deadline ON POST(job_deadline);
CREATE INDEX idx_post_job_region ON POST(job_region);
CREATE INDEX idx_post_job_status ON POST(job_status);
CREATE INDEX idx_post_job_search ON POST(board_type, job_status, job_deadline);

COMMIT;

-- 테이블 생성 확인
SELECT 'ORDERS 테이블 생성 확인' AS INFO FROM DUAL;
SELECT COUNT(*) AS ORDERS_EXISTS FROM USER_TABLES WHERE TABLE_NAME = 'ORDERS';

SELECT 'ORDER_ITEMS 테이블 생성 확인' AS INFO FROM DUAL;
SELECT COUNT(*) AS ORDER_ITEMS_EXISTS FROM USER_TABLES WHERE TABLE_NAME = 'ORDER_ITEMS';

SELECT 'PAYMENTS 테이블 생성 확인' AS INFO FROM DUAL;
SELECT COUNT(*) AS PAYMENTS_EXISTS FROM USER_TABLES WHERE TABLE_NAME = 'PAYMENTS';
