-- ============================================================
-- PortFlux 프로젝트 데이터베이스 스크립트 (수정본)
-- 작성일: 2025-12-30
-- 설명: 전체 테이블 생성 및 샘플 데이터 삽입
-- ============================================================

-- 안전한 테이블 삭제 (존재하는 경우만)
BEGIN
    FOR t IN (SELECT table_name FROM user_tables 
              WHERE table_name IN ('PAYMENTS', 'PAY', 'ORDER_ITEMS', 'ORDERS', 
                                   'COMMENT_LIKE', 'POST_LIKE', 'CART', 
                                   'CHAT_MESSAGE_FILES', 'CHAT_MESSAGES', 
                                   'DIRECT_CHAT_ROOMS', 'FOLLOWS', 'POST_SAVE', 
                                   'POST_COMMENT', 'POST', 'ADMIN_ACCOUNT', 
                                   'COMPANY', 'USERS'))
    LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

------------------------------------------------------------
-- 1) USERS 테이블
------------------------------------------------------------
CREATE TABLE USERS (
    user_num NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR2(50) NOT NULL UNIQUE,
    user_password VARCHAR2(100) NOT NULL,
    user_name VARCHAR2(100) NOT NULL,
    user_phone VARCHAR2(20),
    user_email VARCHAR2(255) NOT NULL,
    user_nickname VARCHAR2(100) NOT NULL,
    drawn_user CHAR(1) DEFAULT 'N',
    user_create_at DATE DEFAULT SYSDATE NOT NULL,
    user_level NUMBER(2),
    user_image BLOB,
    user_banner BLOB
);

------------------------------------------------------------
-- 2) COMPANY 테이블
------------------------------------------------------------
CREATE TABLE COMPANY (
    company_num NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id VARCHAR2(50) NOT NULL UNIQUE,
    company_password VARCHAR2(100) NOT NULL,
    company_name VARCHAR2(100) NOT NULL,
    company_phone VARCHAR2(20) NOT NULL,
    company_email VARCHAR2(255) NOT NULL,
    drawn_company CHAR(1) DEFAULT 'N',
    company_create_at DATE DEFAULT SYSDATE,
    company_image BLOB,
    company_banner BLOB,
    business_number VARCHAR2(20) NOT NULL UNIQUE
);

------------------------------------------------------------
-- 3) ADMIN_ACCOUNT 테이블
------------------------------------------------------------
CREATE TABLE ADMIN_ACCOUNT (
    admin_num NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_num NUMBER(20) NOT NULL,
    admin_id VARCHAR2(50) NOT NULL UNIQUE,
    admin_password VARCHAR2(100) NOT NULL,
    admin_name VARCHAR2(100),
    assigned_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_admin_user FOREIGN KEY (user_num) REFERENCES USERS(user_num) ON DELETE CASCADE
);

COMMENT ON TABLE ADMIN_ACCOUNT IS '관리자 계정 정보';
COMMENT ON COLUMN ADMIN_ACCOUNT.user_num IS 'USERS 테이블의 회원 번호';

------------------------------------------------------------
-- 4) POST 테이블
------------------------------------------------------------
CREATE TABLE POST (
    post_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_type VARCHAR2(10) NOT NULL,
    user_num NUMBER(20),
    company_num NUMBER(20),
    title VARCHAR2(255) NOT NULL,
    content VARCHAR2(4000) NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE DEFAULT SYSDATE NOT NULL,
    view_cnt NUMBER DEFAULT 0,
    price NUMBER(10),
    ai_summary VARCHAR2(500),
    download_cnt NUMBER DEFAULT 0,
    post_file VARCHAR2(255),
    like_cnt NUMBER DEFAULT 0,
    image VARCHAR2(255),
    tags VARCHAR2(2000),
    -- 채용공고 관련 컬럼
    job_region VARCHAR2(100),
    job_career_type VARCHAR2(500),
    job_career_years VARCHAR2(500),
    job_education VARCHAR2(50),
    job_education_exclude CHAR(1) DEFAULT 'N',
    job_salary_min NUMBER(10),
    job_salary_max NUMBER(10),
    job_deadline DATE,
    job_status VARCHAR2(20) DEFAULT 'ACTIVE',
    job_industries VARCHAR2(500),
    job_company_types VARCHAR2(500),
    job_work_types VARCHAR2(500),
    job_work_days VARCHAR2(500),
    -- 제약조건
    CONSTRAINT ck_post_board_type CHECK (board_type IN ('lookup', 'job', 'free', 'notice')),
    CONSTRAINT ck_post_author_unified CHECK (
        ((board_type IN ('free', 'lookup', 'notice')) AND (user_num IS NOT NULL OR company_num IS NOT NULL))
        OR (board_type = 'job' AND company_num IS NOT NULL)
    ),
    CONSTRAINT ck_job_required_fields CHECK (
        (board_type = 'job' AND job_region IS NOT NULL AND job_deadline IS NOT NULL AND job_status IS NOT NULL)
        OR board_type IN ('lookup', 'free', 'notice')
    ),
    CONSTRAINT ck_job_status CHECK (
        job_status IN ('ACTIVE', 'EXPIRED', 'CLOSED') OR job_status IS NULL
    ),
    CONSTRAINT fk_post_user FOREIGN KEY (user_num) REFERENCES USERS(user_num) ON DELETE SET NULL,
    CONSTRAINT fk_post_company FOREIGN KEY (company_num) REFERENCES COMPANY(company_num) ON DELETE SET NULL
);

-- POST 인덱스
CREATE INDEX idx_post_tags ON POST(tags);
CREATE INDEX idx_post_job_deadline ON POST(job_deadline);
CREATE INDEX idx_post_job_region ON POST(job_region);
CREATE INDEX idx_post_job_status ON POST(job_status);
CREATE INDEX idx_post_job_search ON POST(board_type, job_status, job_deadline);

-- POST 트리거
CREATE OR REPLACE TRIGGER trg_post_update
BEFORE UPDATE ON POST
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;
/

------------------------------------------------------------
-- 5) POST_COMMENT 테이블
------------------------------------------------------------
CREATE TABLE POST_COMMENT (
    comment_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id NUMBER(20) NOT NULL,
    user_num NUMBER(20),
    company_num NUMBER(20),
    comment_content VARCHAR2(1000),
    comment_created_at DATE DEFAULT SYSDATE,
    comment_modify_at DATE,
    parent_id NUMBER(20),
    CONSTRAINT ck_comment_author CHECK (user_num IS NOT NULL OR company_num IS NOT NULL),
    CONSTRAINT fk_comment_user FOREIGN KEY (user_num) REFERENCES USERS(user_num) ON DELETE SET NULL,
    CONSTRAINT fk_comment_post FOREIGN KEY (post_id) REFERENCES POST(post_id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_company FOREIGN KEY (company_num) REFERENCES COMPANY(company_num) ON DELETE SET NULL
);

------------------------------------------------------------
-- 6) POST_SAVE 테이블
------------------------------------------------------------
CREATE TABLE POST_SAVE (
    board_save_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_save_time DATE DEFAULT SYSDATE NOT NULL,
    user_num NUMBER(20) NOT NULL,
    post_id NUMBER(20) NOT NULL,
    CONSTRAINT fk_save_user FOREIGN KEY (user_num) REFERENCES USERS(user_num) ON DELETE CASCADE,
    CONSTRAINT fk_save_post FOREIGN KEY (post_id) REFERENCES POST(post_id) ON DELETE CASCADE
);

------------------------------------------------------------
-- 7) FOLLOWS 테이블
------------------------------------------------------------
CREATE TABLE FOLLOWS (
    follow_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id NUMBER(20) NOT NULL,
    following_id NUMBER(20) NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_follows_follower FOREIGN KEY (follower_id) REFERENCES USERS(user_num) ON DELETE CASCADE,
    CONSTRAINT fk_follows_following FOREIGN KEY (following_id) REFERENCES USERS(user_num) ON DELETE CASCADE
);

------------------------------------------------------------
-- 8) DIRECT_CHAT_ROOMS 테이블
------------------------------------------------------------
CREATE TABLE DIRECT_CHAT_ROOMS (
    room_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user1_num NUMBER(20) NOT NULL,
    user2_num NUMBER(20) NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    last_message_at DATE,
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT fk_chatroom_user1 FOREIGN KEY (user1_num) REFERENCES USERS(user_num),
    CONSTRAINT fk_chatroom_user2 FOREIGN KEY (user2_num) REFERENCES USERS(user_num)
);

------------------------------------------------------------
-- 9) CHAT_MESSAGES 테이블
------------------------------------------------------------
CREATE TABLE CHAT_MESSAGES (
    message_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id NUMBER(20) NOT NULL,
    user_num NUMBER(20) NOT NULL,
    sender_num NUMBER(20) NOT NULL,
    content VARCHAR2(2000),
    has_file CHAR(1) DEFAULT 'N' NOT NULL,
    sent_at DATE DEFAULT SYSDATE NOT NULL,
    read_yn CHAR(1) DEFAULT 'N' NOT NULL,
    deleted_yn CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT fk_message_room FOREIGN KEY (room_id) REFERENCES DIRECT_CHAT_ROOMS(room_id) ON DELETE CASCADE,
    CONSTRAINT fk_message_user FOREIGN KEY (user_num) REFERENCES USERS(user_num),
    CONSTRAINT fk_message_sender FOREIGN KEY (sender_num) REFERENCES USERS(user_num)
);

------------------------------------------------------------
-- 10) CHAT_MESSAGE_FILES 테이블
------------------------------------------------------------
CREATE TABLE CHAT_MESSAGE_FILES (
    file_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id NUMBER(20) NOT NULL,
    file_name VARCHAR2(255) NOT NULL,
    mime_type VARCHAR2(100),
    file_size NUMBER(20),
    file_path VARCHAR2(1000),
    file_data BLOB,
    uploaded_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_file_message FOREIGN KEY (message_id) REFERENCES CHAT_MESSAGES(message_id) ON DELETE CASCADE
);

------------------------------------------------------------
-- 11) CART 테이블
------------------------------------------------------------
CREATE TABLE CART (
    cart_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_num NUMBER(20) NOT NULL,
    post_id NUMBER(20) NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_cart_user FOREIGN KEY (user_num) REFERENCES USERS(user_num) ON DELETE CASCADE,
    CONSTRAINT fk_cart_post FOREIGN KEY (post_id) REFERENCES POST(post_id) ON DELETE CASCADE
);

------------------------------------------------------------
-- 12) ORDERS 테이블 (주문 내역 관리)
------------------------------------------------------------
CREATE TABLE ORDERS (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id NUMBER(20) NOT NULL,
    merchant_uid VARCHAR2(255) NOT NULL,
    total_amount NUMBER(19,2) NOT NULL,
    status VARCHAR2(50) NOT NULL,
    imp_uid VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_orders_merchant_uid UNIQUE (merchant_uid),
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES USERS(user_num)
);

CREATE INDEX idx_orders_merchant_uid ON ORDERS(merchant_uid);
CREATE INDEX idx_orders_user_id ON ORDERS(user_id);
CREATE INDEX idx_orders_created_at ON ORDERS(created_at);

COMMENT ON TABLE ORDERS IS '주문 내역 관리 테이블';
COMMENT ON COLUMN ORDERS.merchant_uid IS '주문 고유 식별자 (UUID 기반)';
COMMENT ON COLUMN ORDERS.status IS '주문 상태 (CREATED, PENDING, PAID, CANCELLED)';

------------------------------------------------------------
-- 13) ORDER_ITEMS 테이블 (주문 상품 상세)
------------------------------------------------------------
CREATE TABLE ORDER_ITEMS (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    product_id NUMBER(20) NOT NULL,
    product_name VARCHAR2(500) NOT NULL,
    unit_price NUMBER(19,2) NOT NULL,
    qty NUMBER NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES ORDERS(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES POST(post_id)
);

CREATE INDEX idx_order_items_order_id ON ORDER_ITEMS(order_id);
CREATE INDEX idx_order_items_product_id ON ORDER_ITEMS(product_id);

COMMENT ON TABLE ORDER_ITEMS IS '주문 상품 상세 정보';
COMMENT ON COLUMN ORDER_ITEMS.qty IS '주문 수량';

------------------------------------------------------------
-- 14) POST_LIKE 테이블 (게시글 좋아요)
------------------------------------------------------------
CREATE TABLE POST_LIKE (
    like_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    post_id NUMBER(20) NOT NULL,
    user_num NUMBER(20),
    company_num NUMBER(20),
    liked_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uq_post_like_unified UNIQUE (post_id, user_num, company_num),
    CONSTRAINT ck_like_author CHECK (user_num IS NOT NULL OR company_num IS NOT NULL),
    CONSTRAINT fk_postlike_user FOREIGN KEY (user_num) REFERENCES USERS(user_num) ON DELETE SET NULL,
    CONSTRAINT fk_postlike_post FOREIGN KEY (post_id) REFERENCES POST(post_id) ON DELETE CASCADE,
    CONSTRAINT fk_postlike_company FOREIGN KEY (company_num) REFERENCES COMPANY(company_num) ON DELETE SET NULL
);

------------------------------------------------------------
-- 15) COMMENT_LIKE 테이블 (댓글 좋아요)
------------------------------------------------------------
CREATE TABLE COMMENT_LIKE (
    like_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_num NUMBER(20) NOT NULL,
    comment_id NUMBER(20) NOT NULL,
    liked_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uq_comment_like UNIQUE (user_num, comment_id),
    CONSTRAINT fk_commentlike_user FOREIGN KEY (user_num) REFERENCES USERS(user_num) ON DELETE CASCADE,
    CONSTRAINT fk_commentlike_comment FOREIGN KEY (comment_id) REFERENCES POST_COMMENT(comment_id) ON DELETE CASCADE
);

------------------------------------------------------------
-- 16) PAYMENTS 테이블 (결제 기록 - 아임포트 연동)
------------------------------------------------------------
CREATE TABLE PAYMENTS (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    imp_uid VARCHAR2(255) NOT NULL,
    merchant_uid VARCHAR2(255) NOT NULL,
    amount NUMBER(19,2) NOT NULL,
    status VARCHAR2(50) NOT NULL,
    paid_at TIMESTAMP,
    raw_response CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_payments_imp_uid UNIQUE (imp_uid),
    CONSTRAINT uq_payments_merchant_uid UNIQUE (merchant_uid),
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES ORDERS(id) ON DELETE CASCADE
);

CREATE INDEX idx_payments_order_id ON PAYMENTS(order_id);
CREATE INDEX idx_payments_merchant_uid ON PAYMENTS(merchant_uid);
CREATE INDEX idx_payments_imp_uid ON PAYMENTS(imp_uid);
CREATE INDEX idx_payments_status ON PAYMENTS(status);

COMMENT ON TABLE PAYMENTS IS '결제 기록 관리 테이블 (아임포트 연동)';
COMMENT ON COLUMN PAYMENTS.imp_uid IS '아임포트 거래 고유 ID';
COMMENT ON COLUMN PAYMENTS.merchant_uid IS '가맹점 주문 번호 (ORDERS.merchant_uid)';
COMMENT ON COLUMN PAYMENTS.status IS '결제 상태 (READY, PAID, CANCELLED, REFUNDED)';
COMMENT ON COLUMN PAYMENTS.raw_response IS '아임포트 응답 원본 데이터 (JSON)';

------------------------------------------------------------
-- 17) PAY 테이블 (기존 결제 테이블 유지)
------------------------------------------------------------
CREATE TABLE PAY (
    order_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_num NUMBER(20) NOT NULL,
    pay_date DATE DEFAULT SYSDATE,
    pay_price NUMBER(20) NOT NULL,
    setle_sttus NUMBER(1) NOT NULL,
    order_name VARCHAR2(200) NOT NULL,
    cart_id NUMBER(20) NOT NULL,
    CONSTRAINT fk_pay_user FOREIGN KEY (user_num) REFERENCES USERS(user_num) ON DELETE CASCADE,
    CONSTRAINT fk_pay_cart FOREIGN KEY (cart_id) REFERENCES CART(cart_id) ON DELETE CASCADE
);

COMMIT;

-- ============================================================
-- 샘플 데이터 INSERT
-- ============================================================

-- 1) USERS
INSERT INTO USERS (user_id, user_password, user_name, user_phone, user_email, user_nickname, user_level)
VALUES ('user001', 'password123!', '김철수', '010-1234-5678', 'kimcs@email.com', '철수짱', 1);

INSERT INTO USERS (user_id, user_password, user_name, user_phone, user_email, user_nickname, user_level)
VALUES ('user002', 'password456!', '이영희', '010-9876-5432', 'leeyh@email.com', '영희네', 2);

-- 1-1) Admin
INSERT INTO USERS (user_id, user_password, user_name, user_phone, user_email, user_nickname)
VALUES ('admin', 'admin123!', '관리자', '010-0000-0000', 'admin@portflux.com', '관리자');

INSERT INTO ADMIN_ACCOUNT (user_num, admin_id, admin_password, admin_name)
SELECT user_num, 'admin', 'admin123!', '관리자'
FROM USERS WHERE user_id = 'admin';

-- 2) COMPANY
INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('company001', 'comp123!', '테크스타트업', '02-1234-5678', 'contact@techstartup.com', '123-45-67890');

INSERT INTO COMPANY (company_id, company_password, company_name, company_phone, company_email, business_number)
VALUES ('company002', 'comp456!', '디자인에이전시', '02-9876-5432', 'hello@designagency.com', '987-65-43210');

-- 3) POST
INSERT INTO POST (board_type, user_num, title, content, price, ai_summary, download_cnt, post_file, view_cnt)
VALUES ('lookup', 1, 'Python 머신러닝 완벽 가이드', 'Python으로 머신러닝을 배우는 완벽한 자료입니다. 초보자부터 고급까지 모두 학습 가능합니다.',
        15000, 'Python 머신러닝 학습 자료로 초보부터 고급까지 단계별 학습 가능', 25, 'python_ml_guide.pdf', 150);

INSERT INTO POST (board_type, user_num, title, content, price, ai_summary, download_cnt, post_file, view_cnt)
VALUES ('lookup', 2, 'React 프로젝트 템플릿 모음', 'React로 만든 다양한 프로젝트 템플릿 10종입니다. 즉시 사용 가능한 코드가 포함되어 있습니다.',
        20000, 'React 프로젝트 템플릿 10종 모음, 즉시 사용 가능', 40, 'react_templates.zip', 230);

INSERT INTO POST (board_type, company_num, title, content, view_cnt,
                  job_region, job_career_type, job_career_years, 
                  job_education, job_education_exclude,
                  job_deadline, job_status,
                  job_industries, job_company_types, job_work_types, job_work_days)
VALUES ('job', 1, '[테크스타트업] 백엔드 개발자 채용',
        '저희 테크스타트업에서 백엔드 개발자를 모집합니다. 주요 업무: Spring Boot 기반 API 개발, AWS 인프라 구축 및 관리', 320,
        'seoul_gangnam', '["경력무관"]', '[]',
        NULL, 'Y',
        SYSDATE + 30, 'ACTIVE',
        '["IT·웹·통신"]', '["중소기업"]', '["정규직"]', '["주 5일(월~금)"]');

INSERT INTO POST (board_type, company_num, title, content, view_cnt,
                  job_region, job_career_type, job_career_years,
                  job_education, job_education_exclude,
                  job_deadline, job_status,
                  job_industries, job_company_types, job_work_types, job_work_days)
VALUES ('job', 2, '[디자인에이전시] UI/UX 디자이너 채용',
        '디자인에이전시에서 UI/UX 디자이너를 채용합니다. 담당 업무: 웹/앱 서비스 UI/UX 디자인', 180,
        'seoul_gangnam', '["경력무관"]', '[]',
        NULL, 'Y',
        SYSDATE + 30, 'ACTIVE',
        '["IT·웹·통신"]', '["중소기업"]', '["정규직"]', '["주 5일(월~금)"]');

INSERT INTO POST (board_type, user_num, title, content, view_cnt)
VALUES ('free', 1, '오라클 DB 설치 중 에러 해결 방법',
        '오라클 19c 설치하다가 ORA-12154 에러가 발생했어요. 해결 방법 공유합니다.', 85);

INSERT INTO POST (board_type, user_num, title, content, view_cnt)
VALUES ('free', 2, 'Spring Boot 프로젝트 구조 추천해주세요',
        '처음으로 Spring Boot로 큰 프로젝트를 시작하는데요. 패키지 구조 조언 부탁드립니다.', 120);

-- 4) POST_COMMENT
INSERT INTO POST_COMMENT (user_num, post_id, comment_content)
VALUES (2, 1, '자료 정말 유익하네요! 다운로드해서 공부하겠습니다.');

INSERT INTO POST_COMMENT (user_num, post_id, comment_content)
VALUES (1, 1, '감사합니다! 많은 도움이 되셨으면 좋겠어요~');

-- 5) POST_SAVE
INSERT INTO POST_SAVE (user_num, post_id) VALUES (1, 2);
INSERT INTO POST_SAVE (user_num, post_id) VALUES (2, 1);

-- 6) FOLLOWS
INSERT INTO FOLLOWS (follower_id, following_id) VALUES (1, 2);
INSERT INTO FOLLOWS (follower_id, following_id) VALUES (2, 1);

-- 7) DIRECT_CHAT_ROOMS
INSERT INTO DIRECT_CHAT_ROOMS (user1_num, user2_num, status) VALUES (1, 2, 'ACTIVE');

-- 8) CHAT_MESSAGES
INSERT INTO CHAT_MESSAGES (room_id, user_num, sender_num, content) VALUES (1, 2, 1, '안녕하세요!');

-- 10) CART
INSERT INTO CART (user_num, post_id) VALUES (1, 1);
INSERT INTO CART (user_num, post_id) VALUES (2, 2);

-- 11) ORDERS
INSERT INTO ORDERS (user_id, merchant_uid, total_amount, status)
VALUES (1, 'ORD-20251230-001', 35000, 'PENDING');

-- 12) ORDER_ITEMS
INSERT INTO ORDER_ITEMS (order_id, product_id, product_name, unit_price, qty)
VALUES (1, 1, 'Python 머신러닝 완벽 가이드', 15000, 1);

INSERT INTO ORDER_ITEMS (order_id, product_id, product_name, unit_price, qty)
VALUES (1, 2, 'React 프로젝트 템플릿 모음', 20000, 1);

-- 13) POST_LIKE
INSERT INTO POST_LIKE (user_num, post_id) VALUES (1, 1);
INSERT INTO POST_LIKE (user_num, post_id) VALUES (2, 1);

-- 14) COMMENT_LIKE
INSERT INTO COMMENT_LIKE (user_num, comment_id) VALUES (2, 1);

-- 추가 채용공고 샘플 데이터
INSERT INTO POST (
    board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days
) VALUES (
    'job', 1, 'ULTRAFIT 웹 디자이너 신입 채용',
    '웹 디자이너 신입 채용합니다. 성장 가능성이 높은 회사입니다. 주요 업무: 브랜딩 디자인 등',
    'seoul_gangnam', '["신입"]', '[]',
    'university', 'N',
    NULL, NULL, SYSDATE + 30, 'ACTIVE',
    '["IT·웹·통신"]', '["스타트업"]', '["정규직"]', '["주 5일(월~금)"]'
);

INSERT INTO POST (
    board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days
) VALUES (
    'job', 1, '구매 담당 경력직 채용',
    '글로벌 유통회사에서 구매 담당자를 모집합니다. 복리후생: 연봉 3000~5000만원, 4대 보험, 퇴직금',
    'seoul_gangnam', '["경력"]', '["5년", "6년", "7년"]',
    'college_2_3', 'N',
    3000, 5000, SYSDATE + 7, 'ACTIVE',
    '["유통·무역"]', '["중견기업"]', '["정규직"]', '["주 5일(월~금)"]'
);

INSERT INTO POST (
    board_type, company_num, title, content,
    job_region, job_career_type, job_career_years,
    job_education, job_education_exclude,
    job_salary_min, job_salary_max, job_deadline, job_status,
    job_industries, job_company_types, job_work_types, job_work_days
) VALUES (
    'job', 2, '편집디자이너 경력 채용',
    '광고 대행사에서 편집디자이너를 채용합니다. 주 5일 근무, 마포구 소재.',
    'seoul_mapo', '["경력"]', '["3년", "4년", "5년"]',
    'high', 'N',
    2500, 4000, SYSDATE + 14, 'ACTIVE',
    '["미디어·광고"]', '["중소기업"]', '["정규직", "계약직"]', '["주 5일(월~금)"]'
);

COMMIT;

-- ============================================================
-- 데이터 확인
-- ============================================================

SELECT 'USERS' AS 테이블명, COUNT(*) AS 데이터개수 FROM USERS
UNION ALL
SELECT 'COMPANY', COUNT(*) FROM COMPANY
UNION ALL
SELECT 'POST', COUNT(*) FROM POST
UNION ALL
SELECT 'POST_COMMENT', COUNT(*) FROM POST_COMMENT
UNION ALL
SELECT 'POST_SAVE', COUNT(*) FROM POST_SAVE
UNION ALL
SELECT 'FOLLOWS', COUNT(*) FROM FOLLOWS
UNION ALL
SELECT 'DIRECT_CHAT_ROOMS', COUNT(*) FROM DIRECT_CHAT_ROOMS
UNION ALL
SELECT 'CHAT_MESSAGES', COUNT(*) FROM CHAT_MESSAGES
UNION ALL
SELECT 'CHAT_MESSAGE_FILES', COUNT(*) FROM CHAT_MESSAGE_FILES
UNION ALL
SELECT 'CART', COUNT(*) FROM CART
UNION ALL
SELECT 'ORDERS', COUNT(*) FROM ORDERS
UNION ALL
SELECT 'ORDER_ITEMS', COUNT(*) FROM ORDER_ITEMS
UNION ALL
SELECT 'POST_LIKE', COUNT(*) FROM POST_LIKE
UNION ALL
SELECT 'COMMENT_LIKE', COUNT(*) FROM COMMENT_LIKE
UNION ALL
SELECT 'PAYMENTS', COUNT(*) FROM PAYMENTS
UNION ALL
SELECT 'PAY', COUNT(*) FROM PAY;